spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  application:
    name: media-service
  


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_INSTANCE_HOSTNAME:http://localhost}:8761/eureka/