spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #############--------USER-------------#############
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        ##############------PRODUCT------T##################
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        ################------MEDIA---------################
        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/v1/medias/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://www.buy01.site"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true


server:
  port: 8222
  ssl:
    enabled: true
    key-store: classpath:keystore/keystore.p12
    key-store-password: Dinamo22**
    key-store-type: PKCS12

eureka:
  instance:
    prefer-ip-address: true        # ðŸ‘ˆ force Eureka Ã  utiliser ton IP locale
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}    #ðŸ‘ˆ (optionnel) force l'utilisation de localhost
    instance-id: ${spring.application.name}:${server.port}
